CREATE TABLE IF NOT EXISTS books (
  id INT PRIMARY KEY AUTO_INCREMENT,
  book_name_id INT NOT NULL,
  class VARCHAR(10) NOT NULL,
  price DECIMAL(5) NOT NULL,
  quantity INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (book_name_id) REFERENCES booknames(id) ON DELETE CASCADE
); 